### ISSUE TITLE
nbclient.exceptions.DeadKernelError: Kernel died error occured

### ISSUE THREAD

**Issue by tkoyama010** [jupyter/jupyter-sphinx#176]
Thank you for cool extension to Sphinx.
I made the following Dockerfile which is using `jupyter_sphinx`.

```Dockerfile
FROM python:3.7

RUN apt update; apt install -y git make python3-pip python-qt4 libgl1-mesa-glx
RUN git clone https://github.com/tkoyama010/pyvista-doc-translations.git
WORKDIR /pyvista-doc-translations
RUN git checkout b594ebbe4b8020b573107c1b231eb391859508bc
RUN git submodule sync
RUN git submodule update --init --force --recursive pyvista
RUN pip3 install -r requirements.txt
RUN pip3 install Sphinx
RUN sphinx-build -D language=en -T . _build/html
```
The following error occured and I could not understand what was happing.
Do you have any ideas to fix it?

```bash
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/local/lib/python3.7/site-packages/jupyter_sphinx/execute.py", line 259, in execute_cells                                                                                                               
    executenb(notebook, **execute_kwargs)                                                                                                                                                                           
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute                                                                                                                           
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()                                                                                                                                    
  File "/usr/local/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped                                                                                                                               
    return just_run(coro(*args, **kwargs))                                                                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run                                                                                                                              
    return loop.run_until_complete(coro)                                                                                                                                                                            
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete                                                                                                                           
    return future.result()                                                                                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute                                                                                                                      
    cell, index, execution_count=self.code_cells_executed + 1                                                                                                                                                       
  File "/usr/local/lib/python3.7/site-packages/nbclient/client.py", line 845, in async_execute_cell                                                                                                                 
    raise DeadKernelError("Kernel died")                                                                                                                                                                            
nbclient.exceptions.DeadKernelError: Kernel died
```

**Comment by akhmerov** [comment]
Thanks for reporting! This seems like a problem with one of the notebooks: the jupyter kernel is dying while executing the code. That means that the problem is somewhere between jupyter kernels and the code you're running.

The build logs should show which file is being executed when the error occurs, does this happen?

Moving forward, on the jupyter-sphinx side we should catch this error and reraise it with more information.

**Comment by tkoyama010** [comment]
Finally I reproduced the same error using jupyter nbconvert. So it is not related to the jupyter-sphinx. Sorry for the noise. Closing
