### ISSUE TITLE
ModuleNotFoundError: No module named 'ipywidgets.embed'

### ISSUE THREAD

**Issue by sandrotosi** [jupyter/jupyter-sphinx#186]
Hello,
This error happens when building https://github.com/pydata/pydata-sphinx-theme documentation, which uses jupyter-sphinx:

```
sphinx-build -N -E -T -b html . /build/pydata-sphinx-theme-0.6.3/.pybuild/docs/html/
Running Sphinx v3.5.4

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 417, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/jupyter_sphinx/__init__.py", line 13, in <module>
    from .ast import (
  File "/usr/lib/python3/dist-packages/jupyter_sphinx/ast.py", line 16, in <module>
    import ipywidgets.embed
ModuleNotFoundError: No module named 'ipywidgets.embed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 239, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 396, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 420, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension jupyter_sphinx (exception: No module named 'ipywidgets.embed')

Extension error:
Could not import extension jupyter_sphinx (exception: No module named 'ipywidgets.embed')
```

can you have a look? thanks!

**Comment by akhmerov** [comment]
What version of ipywidgets do you have?

**Comment by sandrotosi** [comment]
> What version of ipywidgets do you have?

yeah i think i realized the problem is indeed an outdated ipywidgets version: we currently have version 6,  while r.txt clearly states jupyter-sphinx needs 7+, sorry for the noise
